ci: fix coverage report

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,19 +14,12 @@ on:
   pull_request:
 
 jobs:
-  kotlin:
-    name: Run Kotlin tests
+  build-kotlin:
+    name: Build Kotlin sources
     timeout-minutes: 30
     runs-on: ubuntu-latest
     permissions:
       contents: read
-    strategy:
-      # Green Software Engineering Practices calls for always using fail-fast.
-      # However, aborting the runs could result in an incomplete report and more CI runs due to overlooked failures.
-      # This is a situation where the savings are so small it's not worth (and may in the end have a net negative impact).
-      fail-fast: false
-      matrix:
-        project: [server, commons, metamodel]
     steps:
       - uses: actions/checkout@v6
         with:
@@ -39,10 +32,48 @@ jobs:
         with:
           # Protect against cache poisoning by NOT using cache in release builds
           cache-disabled: ${{ startsWith(github.ref, 'refs/tags/') }}
+          cache-read-only: false
+
+      - run: ./gradlew classes testClasses
+      - uses: ./.github/actions/upload-kotlin-build
+
+  kotlin:
+    name: Run Kotlin tests
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    needs: build-kotlin
+    strategy:
+      # Green Software Engineering Practices calls for always using fail-fast.
+      # However, aborting the runs could result in an incomplete report and more CI runs due to overlooked failures.
+      # This is a situation where the savings are so small it's not worth (and may in the end have a net negative impact).
+      fail-fast: false
+      matrix:
+        project: [server, commons]
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: jdx/mise-action@v4  # zizmor: ignore[cache-poisoning] -- Cache disabled in sensitive runs
+        with:
+          # Protect against cache poisoning by NOT using cache in release builds
+          cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
+      - uses: gradle/actions/setup-gradle@v6 # zizmor: ignore[cache-poisoning] -- Cache disabled in sensitive runs
+        with:
+          # Protect against cache poisoning by NOT using cache in release builds
+          cache-disabled: ${{ startsWith(github.ref, 'refs/tags/') }}
+          cache-read-only: true  # Cache has already been warmed up, no need to waste time uploading it again
+      - uses: ./.github/actions/download-kotlin-build
 
       # Not ideal but it works...
       - run: docker compose up --wait postgres storage
-      - run: ./gradlew :"$PROJECT":koverXmlReport
+        if: matrix.project == 'server'
+
+      # Explicitly skip compile tasks to force the use of the restored ones above.
+      - name: Run tests
+        run: ./gradlew :"$PROJECT":test :"$PROJECT":koverBinaryReport
+          -x :build-logic:jar -x classes -x testClasses -x compileKotlin -x compileTestKotlin
         env:
           PROJECT: ${{ matrix.project }}
 
@@ -51,44 +82,88 @@ jobs:
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: ${{ matrix.project }}/build/test-results/test/TEST-*.xml
+          truncate_stack_traces: false
+          annotate_only: true
 
       - name: Upload coverage report
         uses: actions/upload-artifact@v7
+        if: success() || failure() # always run even if the previous step fails
         with:
-          name: kotlin-codecov-report-${{ matrix.project }}
-          path: ${{ matrix.project }}/build/reports/kover/report.xml
+          name: kotlin-codecov-report-raw-${{ matrix.project }}
+          path: ${{ matrix.project }}/build/kover
+          include-hidden-files: true
 
-  kotlin-codecov-report:
-    name: Aggregate code coverage reports
+  kotlin-codecov-aggregate:
+    name: Aggregate coverage reports
     timeout-minutes: 5
     runs-on: ubuntu-slim
     permissions:
-      pull-requests: write  # Required to publish/update coverage report comment
+      contents: read
     needs: kotlin
     steps:
-      - name: Merge coverage reports
-        uses: actions/upload-artifact/merge@v7
+      - uses: actions/upload-artifact/merge@v7
         with:
-          name: kotlin-codecov-report
-          pattern: kotlin-codecov-report-*
+          name: kotlin-codecov-report-raw
+          pattern: kotlin-codecov-report-raw-*
+          include-hidden-files: true
           separate-directories: true
           delete-merged: true
 
+  kotlin-codecov-report:
+    name: Publish coverage reports
+    timeout-minutes: 10
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write  # Required to publish/update coverage report comment
+    needs: kotlin-codecov-aggregate
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: jdx/mise-action@v4  # zizmor: ignore[cache-poisoning] -- Cache disabled in sensitive runs
+        with:
+          # Protect against cache poisoning by NOT using cache in release builds
+          cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
+      - uses: gradle/actions/setup-gradle@v6  # zizmor: ignore[cache-poisoning] -- Cache disabled in sensitive runs
+        with:
+          # Protect against cache poisoning by NOT using cache in release builds
+          cache-disabled: ${{ startsWith(github.ref, 'refs/tags/') }}
+          cache-read-only: true  # Cache has already been warmed up, no need to waste time uploading it again
+
+      - uses: ./.github/actions/download-kotlin-build
       - name: Download coverage reports
         uses: actions/download-artifact@v8
         with:
-          name: kotlin-codecov-report
+          name: kotlin-codecov-report-raw
+
+      - name: Prepare coverage reports for Kover
+        run: |
+          subprojects=(commons server)
+          for sp in "${subprojects[@]}"; do
+            mv "$GITHUB_WORKSPACE/kotlin-codecov-report-raw-$sp" "$GITHUB_WORKSPACE/$sp/build/kover"
+          done
+        env:
+          GHA_DEBUG: ${{ runner.debug == '1' && 'true' || 'false' }}
+
+      # Explicitly skip Kover artefact generation to force the use of the restored ones above.
+      - run: ./gradlew :koverXmlReport :koverHtmlReport -x :build-logic:jar -x koverGenerateArtifact
 
       - name: Publish coverage report
         uses: mi-kas/kover-report@v2
+        if: success() || failure() # always run even if the previous step fails
         with:
-          path: |
-            ${{ github.workspace }}/kotlin-codecov-report-server/report.xml
-            ${{ github.workspace }}/kotlin-codecov-report-commons/report.xml
-            ${{ github.workspace }}/kotlin-codecov-report-metamodel/report.xml
+          path: build/reports/kover/report.xml
           title: Code Coverage
           update-comment: true
           # TODO: enable these? :)
           #min-coverage-overall: 80
           #min-coverage-changed-files: 80
           coverage-counter-type: BRANCH
+
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v7
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          name: kotlin-codecov-report
+          path: build/reports/kover
